"""
vLLM Ascend NPU 全部 87 项优化配置的结构化编码。
每项包含：唯一 ID、类别、配置类型、启用检查、瓶颈触发条件、关键词、评分参数等。

config_type: env_var | serve_arg | serve_arg_remove | serve_arg_value | additional_config | compile_config | auto
action_type: enable (建议开启) | tune (建议调参) | skip (自动启用不可调)
"""

OPTIMIZATION_ITEMS = [
    # ============================================================
    # 一、vLLM 通用配置 — 1.1 调度配置 (序号 1-7)
    # ============================================================
    {
        "id": "max_num_batched_tokens", "seq": 1,
        "name": "调大 max-num-batched-tokens",
        "category": "scheduling", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--max-num-batched-tokens"},
        "default_enabled": True, "default_value": "2048",
        "operation": "添加或增大 `--max-num-batched-tokens 65536`",
        "tuning_guidance": "增大可提升 GPU 利用率和吞吐，需配合显存容量；设置过小会劣化端到端性能",
        "expected_effect": "增大批处理容量，提升吞吐量",
        "risk": "中",
        "priority": 5,
        "bottleneck_triggers": [
            {"dim": "compute_ratio", "op": "lte", "val": 0.5, "weight": 0.6},
        ],
        "keywords": ["batched_tokens", "batch", "吞吐", "throughput", "调度", "scheduling", "max_num_batched_tokens"],
        "conflicts_with": [], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "max_num_seqs", "seq": 2,
        "name": "设置 max-num-seqs",
        "category": "scheduling", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--max-num-seqs"},
        "default_enabled": True, "default_value": "128",
        "operation": "添加 `--max-num-seqs 1024`，设置推理最大并发数",
        "tuning_guidance": "增大可提升 batch 并行度，但增加显存占用",
        "expected_effect": "提升最大并发处理能力，充分利用 NPU 算力",
        "risk": "低",
        "priority": 4,
        "bottleneck_triggers": [
            {"dim": "compute_ratio", "op": "lte", "val": 0.5, "weight": 0.4},
        ],
        "keywords": ["并发", "concurrency", "max_num_seqs", "调度", "scheduling", "QPS"],
        "conflicts_with": [], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "enable_chunked_prefill", "seq": 3,
        "name": "启用 chunked prefill",
        "category": "scheduling", "config_type": "serve_arg", "action_type": "skip",
        "enabled_check": {"type": "serve_arg_present", "arg": "--enable-chunked-prefill"},
        "default_enabled": True, "default_value": None,
        "operation": "添加 `--enable-chunked-prefill`",
        "tuning_guidance": "开启可降低 TTFT 并提升混合负载吞吐",
        "expected_effect": "将长 prefill 拆分为多个 chunk 与 decode 交错执行",
        "risk": "低", "priority": 5,
        "bottleneck_triggers": [], "keywords": ["chunked", "prefill", "TTFT"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "max_num_partial_prefills", "seq": 4,
        "name": "调大 max-num-partial-prefills",
        "category": "scheduling", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--max-num-partial-prefills"},
        "default_enabled": True, "default_value": "1",
        "operation": "添加 `--max-num-partial-prefills 2` 允许多个 prefill 并发",
        "tuning_guidance": ">1 允许多个 prefill 并发，配合 chunked_prefill 使用",
        "expected_effect": "多 prefill 并发降低排队延迟",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["prefill", "partial", "TTFT", "排队"],
        "conflicts_with": [], "requires": ["enable_chunked_prefill"], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "long_prefill_token_threshold", "seq": 5,
        "name": "设置 long-prefill-token-threshold",
        "category": "scheduling", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--long-prefill-token-threshold"},
        "default_enabled": True, "default_value": "auto",
        "operation": "添加 `--long-prefill-token-threshold 4096`",
        "tuning_guidance": "配合 max_num_partial_prefills 区分长短请求",
        "expected_effect": "区分长短请求，允许短 prompt 插队",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["prefill", "long", "threshold"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "max_long_partial_prefills", "seq": 6,
        "name": "设置 max-long-partial-prefills",
        "category": "scheduling", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--max-long-partial-prefills"},
        "default_enabled": True, "default_value": "1",
        "operation": "添加 `--max-long-partial-prefills 1`",
        "tuning_guidance": "允许短 prompt 插队长 prompt",
        "expected_effect": "降低短请求排队延迟",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["prefill", "long", "partial"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "scheduling_policy", "seq": 7,
        "name": "调度策略 priority",
        "category": "scheduling", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_value", "arg": "--scheduling-policy", "value": "priority"},
        "default_enabled": True, "default_value": "fcfs",
        "operation": "添加 `--scheduling-policy priority`",
        "tuning_guidance": "priority 模式可按优先级调度",
        "expected_effect": "按优先级调度请求",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["scheduling", "priority", "调度"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    # ============================================================
    # 一、1.2 缓存配置 (序号 8-15)
    # ============================================================
    {
        "id": "gpu_memory_utilization", "seq": 8,
        "name": "提高 gpu-memory-utilization",
        "category": "memory", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--gpu-memory-utilization"},
        "default_enabled": True, "default_value": "0.9",
        "operation": "添加 `--gpu-memory-utilization 0.95`，提高推理可用显存比例",
        "tuning_guidance": "越高可分配更多 KV 缓存块，过高会导致 OOM",
        "expected_effect": "增大 KV cache 容量，支持更多并发请求或更长序列",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "gpu_mem_util", "op": "lte", "val": 0.9, "weight": 0.6},
        ],
        "keywords": ["memory", "显存", "KV cache", "OOM", "gpu_memory_utilization"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "block_size", "seq": 9,
        "name": "调整 block-size",
        "category": "memory", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--block-size"},
        "default_enabled": True, "default_value": "auto",
        "operation": "添加 `--block-size 16`",
        "tuning_guidance": "影响内存碎片和缓存效率",
        "expected_effect": "优化 KV cache 块大小，减少内存碎片",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["block_size", "KV cache", "碎片"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "swap_space", "seq": 10,
        "name": "增大 swap-space",
        "category": "memory", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--swap-space"},
        "default_enabled": True, "default_value": "4",
        "operation": "添加 `--swap-space 8`",
        "tuning_guidance": "增大可减少请求抢占",
        "expected_effect": "减少请求抢占，提升吞吐稳定性",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["swap", "抢占", "preemption"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "enable_prefix_caching", "seq": 11,
        "name": "启用 prefix caching",
        "category": "memory", "config_type": "serve_arg", "action_type": "skip",
        "enabled_check": {"type": "serve_arg_present", "arg": "--enable-prefix-caching"},
        "default_enabled": True, "default_value": None,
        "operation": "添加 `--enable-prefix-caching`",
        "tuning_guidance": "相同前缀请求复用 KV 缓存",
        "expected_effect": "减少重复计算，降低 TTFT",
        "risk": "低", "priority": 5,
        "bottleneck_triggers": [], "keywords": ["prefix", "caching", "TTFT"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "prefix_caching_hash_algo", "seq": 12,
        "name": "prefix caching 哈希算法",
        "category": "memory", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_value", "arg": "--prefix-caching-hash-algo", "value": "xxhash"},
        "default_enabled": True, "default_value": "sha256",
        "operation": "添加 `--prefix-caching-hash-algo xxhash`",
        "tuning_guidance": "xxhash 更快",
        "expected_effect": "加速前缀匹配",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["prefix", "hash", "xxhash"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "cpu_offload_gb", "seq": 13,
        "name": "CPU 卸载",
        "category": "memory", "config_type": "serve_arg_value", "action_type": "enable",
        "enabled_check": {"type": "serve_arg_present", "arg": "--cpu-offload-gb"},
        "default_enabled": False, "default_value": "0",
        "operation": "添加 `--cpu-offload-gb 10`",
        "tuning_guidance": "虚拟扩展 GPU 显存，增加延迟",
        "expected_effect": "扩展可用显存，支持更大模型或更多并发",
        "risk": "中", "priority": 3,
        "bottleneck_triggers": [
            {"dim": "gpu_mem_util", "op": "gte", "val": 0.95, "weight": 0.7},
        ],
        "keywords": ["offload", "显存", "OOM", "memory"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "num_gpu_blocks_override", "seq": 14,
        "name": "手动覆盖 GPU 块数",
        "category": "memory", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--num-gpu-blocks-override"},
        "default_enabled": False, "default_value": None,
        "operation": "添加 `--num-gpu-blocks-override 2000`",
        "tuning_guidance": "跳过 profiling 直接指定块数",
        "expected_effect": "精确控制 KV cache 容量",
        "risk": "中", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["gpu_blocks", "KV cache"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "kv_sharing_fast_prefill", "seq": 15,
        "name": "KV 共享快速预填充",
        "category": "memory", "config_type": "serve_arg", "action_type": "skip",
        "enabled_check": {"type": "always_false"},
        "default_enabled": False, "default_value": None,
        "operation": "配置 kv_sharing_fast_prefill 参数",
        "tuning_guidance": "YOCO 等架构中部分层可跳过 prefill",
        "expected_effect": "减少 prefill 计算量",
        "risk": "低", "priority": 1,
        "bottleneck_triggers": [], "keywords": ["kv_sharing", "YOCO"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    # ============================================================
    # 一、1.3 并行配置 (序号 16-23)
    # ============================================================
    {
        "id": "tensor_parallel_size", "seq": 16,
        "name": "增大 tensor-parallel-size",
        "category": "parallel", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--tensor-parallel-size"},
        "default_enabled": True, "default_value": "1",
        "operation": "添加 `--tensor-parallel-size N`，将模型权重分片到多 GPU",
        "tuning_guidance": "增大 TP 可降低单卡计算压力，但增加通信开销",
        "expected_effect": "降低单卡计算压力，为更高并发留出余量",
        "risk": "中", "priority": 5,
        "bottleneck_triggers": [
            {"dim": "compute_ratio", "op": "gte", "val": 0.7, "weight": 0.6},
            {"dim": "tp_size", "op": "eq", "val": 1, "weight": 0.5},
        ],
        "keywords": ["tensor_parallel", "tp", "并行", "多卡", "parallel"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "pipeline_parallel_size", "seq": 17,
        "name": "启用 pipeline-parallel",
        "category": "parallel", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--pipeline-parallel-size"},
        "default_enabled": True, "default_value": "1",
        "operation": "添加 `--pipeline-parallel-size N`",
        "tuning_guidance": "将模型层分配到多 GPU，xlite 不兼容 PP>1",
        "expected_effect": "支持更大模型，降低单卡显存需求",
        "risk": "中", "priority": 3,
        "bottleneck_triggers": [],
        "keywords": ["pipeline_parallel", "pp", "并行"],
        "conflicts_with": ["xlite_graph_enabled"], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "data_parallel_size", "seq": 18,
        "name": "启用 data-parallel",
        "category": "parallel", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "serve_arg_present", "arg": "--data-parallel-size"},
        "default_enabled": True, "default_value": "1",
        "operation": "添加 `--data-parallel-size N`",
        "tuning_guidance": "多副本并行处理请求，线性提升吞吐",
        "expected_effect": "线性提升吞吐量",
        "risk": "低", "priority": 4,
        "bottleneck_triggers": [],
        "keywords": ["data_parallel", "dp", "吞吐", "throughput"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "prefill_context_parallel_size", "seq": 19,
        "name": "预填充上下文并行",
        "category": "parallel", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "1",
        "operation": "配置 prefill_context_parallel_size", "tuning_guidance": "将长序列 prefill 分片到多 GPU",
        "expected_effect": "加速长序列 prefill", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["context_parallel", "prefill", "长序列"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "decode_context_parallel_size", "seq": 20,
        "name": "解码上下文并行",
        "category": "parallel", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "1",
        "operation": "配置 decode_context_parallel_size", "tuning_guidance": "将 decode 阶段注意力计算分片",
        "expected_effect": "加速 decode 阶段", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["context_parallel", "decode"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "enable_expert_parallel", "seq": 21,
        "name": "Expert Parallel (MoE)",
        "category": "parallel", "config_type": "serve_arg", "action_type": "enable",
        "enabled_check": {"type": "serve_arg_present", "arg": "--enable-expert-parallel"},
        "default_enabled": False, "default_value": None,
        "operation": "添加 `--enable-expert-parallel`，对 MoE 模型启用专家并行",
        "tuning_guidance": "MoE 模型下均衡专家负载，减少通信量",
        "expected_effect": "MoE 模型下均衡专家负载，减少通信量，提升吞吐",
        "risk": "低", "priority": 7,
        "bottleneck_triggers": [
            {"dim": "is_moe", "op": "eq", "val": True, "weight": 0.9},
        ],
        "keywords": ["MoE", "expert", "Mixtral", "DeepSeek", "专家并行", "expert_parallel"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "all2all_backend", "seq": 22,
        "name": "MoE 通信后端",
        "category": "communication", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "auto",
        "operation": "自动选择 all2all 后端", "tuning_guidance": "Ascend 默认 flashinfer_all2allv",
        "expected_effect": "优化 MoE 通信", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["all2all", "MoE"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "enable_dbo", "seq": 23,
        "name": "双批次重叠 (DBO)",
        "category": "overlap", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "enable_dbo", "value": True},
        "default_enabled": False, "default_value": None,
        "operation": "添加 `--additional-config '{\"enable_dbo\":true}'`",
        "tuning_guidance": "通信计算 overlap，需 TP>1",
        "expected_effect": "通信与计算重叠，降低通信等待",
        "risk": "中", "priority": 5,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.1, "weight": 0.7},
            {"dim": "tp_size", "op": "gte", "val": 2, "weight": 0.5},
        ],
        "keywords": ["dbo", "overlap", "通信", "communication", "双批次"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency", "throughput"],
    },
    # ============================================================
    # 一、1.4 编译/图优化 (序号 24-28)
    # ============================================================
    {
        "id": "compilation_config_mode", "seq": 24,
        "name": "配置 compilation_config",
        "category": "compile", "config_type": "compile_config", "action_type": "tune",
        "enabled_check": {"type": "compile_config_present"},
        "default_enabled": True, "default_value": "3",
        "operation": "添加 `-cc '{\"mode\":3}'`，启用编译优化",
        "tuning_guidance": "Ascend 通过 torchair 后端编译，mode=3 为推荐值",
        "expected_effect": "启用编译级算子融合优化",
        "risk": "低", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.2, "weight": 0.4},
        ],
        "keywords": ["compilation", "compile", "编译", "torchair", "compilation_config"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "graph_mode", "seq": 25,
        "name": "启用 Graph Mode",
        "category": "dispatch", "config_type": "serve_arg_remove", "action_type": "enable",
        "enabled_check": {"type": "serve_arg_absent", "arg": "--enforce-eager"},
        "default_enabled": False, "default_value": None,
        "operation": "移除 `--enforce-eager`，启用 graph mode 批量下发算子",
        "tuning_guidance": "降低 host scheduling overhead，FULL/PIECEWISE 模式可选",
        "expected_effect": "大幅降低 host scheduling overhead，将 NPU 空闲时间从 >50% 压缩至 <30%",
        "risk": "中",
        "priority": 10,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.3, "weight": 1.0},
            {"dim": "enforce_eager", "op": "eq", "val": True, "weight": 0.8},
        ],
        "keywords": ["free", "空闲", "idle", "host scheduling", "enforce_eager", "graph mode", "图模式", "eager", "算子下发"],
        "conflicts_with": ["task_queue_enable_2"], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "cudagraph_capture_sizes", "seq": 26,
        "name": "图捕获 batch size 列表",
        "category": "compile", "config_type": "compile_config", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "auto",
        "operation": "配置 cudagraph_capture_sizes", "tuning_guidance": "Ascend 用 ACL Graph 替代",
        "expected_effect": "优化图捕获", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["cudagraph", "graph", "capture"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "max_cudagraph_capture_size", "seq": 27,
        "name": "图最大捕获 batch size",
        "category": "compile", "config_type": "compile_config", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "auto",
        "operation": "配置 max_cudagraph_capture_size", "tuning_guidance": "超过此值回退 eager",
        "expected_effect": "控制图捕获范围", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["cudagraph", "max_capture"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "cudagraph_num_of_warmups", "seq": 28,
        "name": "图预热次数",
        "category": "compile", "config_type": "compile_config", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "auto",
        "operation": "配置 cudagraph_num_of_warmups", "tuning_guidance": "影响首次请求延迟",
        "expected_effect": "控制预热开销", "risk": "低", "priority": 1,
        "bottleneck_triggers": [], "keywords": ["warmup", "预热"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    # ============================================================
    # 一、1.5 投机解码 (序号 29-31)
    # ============================================================
    {
        "id": "speculative_decoding", "seq": 29,
        "name": "投机推理加速",
        "category": "speculative", "config_type": "serve_arg", "action_type": "enable",
        "enabled_check": {"type": "serve_arg_present", "arg": "--speculative-config"},
        "default_enabled": False, "default_value": None,
        "operation": "添加 `--speculative-config '{\"method\":\"eagle\",\"num_speculative_tokens\":5}'`",
        "tuning_guidance": "可提升 2-3x decode 吞吐，num_speculative_tokens 需调优",
        "expected_effect": "通过投机采样减少 decode 轮次，提升生成吞吐",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "compute_ratio", "op": "gte", "val": 0.5, "weight": 0.5},
        ],
        "keywords": ["decode", "TPOT", "生成", "吞吐", "speculative", "投机"],
        "conflicts_with": ["xlite_graph_enabled"], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "num_speculative_tokens", "seq": 30,
        "name": "投机 token 数",
        "category": "speculative", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "always_false"}, "default_enabled": False, "default_value": None,
        "operation": "调整 num_speculative_tokens", "tuning_guidance": "越大潜在加速越高但浪费计算",
        "expected_effect": "平衡投机收益与计算开销", "risk": "中", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["speculative", "tokens"],
        "conflicts_with": [], "requires": ["speculative_decoding"], "applicable_when": {"has_speculative": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "draft_tensor_parallel_size", "seq": 31,
        "name": "Draft 模型 TP",
        "category": "speculative", "config_type": "serve_arg_value", "action_type": "tune",
        "enabled_check": {"type": "always_false"}, "default_enabled": False, "default_value": None,
        "operation": "配置 draft_tensor_parallel_size", "tuning_guidance": "通常设为 1",
        "expected_effect": "控制 draft 模型并行度", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["draft", "speculative"],
        "conflicts_with": [], "requires": ["speculative_decoding"], "applicable_when": {"has_speculative": True},
        "optimization_goal": ["throughput"],
    },
    # ============================================================
    # 一、1.6 模型与 Attention (序号 32-33)
    # ============================================================
    {
        "id": "dtype_config", "seq": 32,
        "name": "数据类型配置",
        "category": "compute", "config_type": "serve_arg_value", "action_type": "skip",
        "enabled_check": {"type": "serve_arg_present", "arg": "--dtype"},
        "default_enabled": True, "default_value": "auto",
        "operation": "配置 `--dtype bfloat16`", "tuning_guidance": "bfloat16 在 Ascend 上通常最优",
        "expected_effect": "优化计算精度", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["dtype", "bfloat16", "float16"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "mla_backend", "seq": 33,
        "name": "MLA 注意力后端",
        "category": "compute", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": "auto",
        "operation": "自动选择 MLA 后端", "tuning_guidance": "Ascend 有 AscendMLAImpl",
        "expected_effect": "优化注意力计算", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["MLA", "attention", "flashmla"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    # ============================================================
    # 二、vLLM 环境变量 (序号 34-42)
    # ============================================================
    {
        "id": "vllm_mla_disable", "seq": 34,
        "name": "VLLM_MLA_DISABLE",
        "category": "compute", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_MLA_DISABLE", "value": "0"},
        "default_enabled": True, "default_value": "0",
        "operation": "确保 `export VLLM_MLA_DISABLE=0`", "tuning_guidance": "MLA 可显著减少 KV 缓存",
        "expected_effect": "启用 MLA 优化", "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["MLA", "KV cache"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "vllm_float32_matmul_precision", "seq": 35,
        "name": "float32 矩阵乘精度",
        "category": "compute", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_FLOAT32_MATMUL_PRECISION", "value": "medium"},
        "default_enabled": True, "default_value": "highest",
        "operation": "设置 `export VLLM_FLOAT32_MATMUL_PRECISION=medium`",
        "tuning_guidance": "medium 可提速但降低精度", "expected_effect": "加速 float32 矩阵乘",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["matmul", "precision", "float32"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "vllm_enable_inductor_max_autotune", "seq": 36,
        "name": "Inductor 最大自动调优",
        "category": "compile", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_ENABLE_INDUCTOR_MAX_AUTOTUNE", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置 `export VLLM_ENABLE_INDUCTOR_MAX_AUTOTUNE=1`",
        "tuning_guidance": "Ascend 上效果有限", "expected_effect": "编译调优", "risk": "低", "priority": 1,
        "bottleneck_triggers": [], "keywords": ["inductor", "autotune"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "vllm_enable_inductor_cd_tuning", "seq": 37,
        "name": "Inductor 坐标下降调优",
        "category": "compile", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_ENABLE_INDUCTOR_COORDINATE_DESCENT_TUNING", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置对应环境变量", "tuning_guidance": "Ascend 上效果有限",
        "expected_effect": "编译调优", "risk": "低", "priority": 1,
        "bottleneck_triggers": [], "keywords": ["inductor", "coordinate"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "vllm_kv_cache_layout", "seq": 38,
        "name": "KV Cache 内存布局",
        "category": "memory", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_KV_CACHE_LAYOUT", "value": "NHD"},
        "default_enabled": True, "default_value": "auto",
        "operation": "设置 `export VLLM_KV_CACHE_LAYOUT=NHD`", "tuning_guidance": "影响内存访问模式",
        "expected_effect": "优化内存访问", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["kv_cache", "layout", "NHD"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "vllm_v1_output_proc_chunk_size", "seq": 39,
        "name": "V1 输出处理 chunk size",
        "category": "scheduling", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_V1_OUTPUT_PROC_CHUNK_SIZE", "value": "128"},
        "default_enabled": True, "default_value": "128",
        "operation": "设置对应环境变量", "tuning_guidance": "纯 Python 逻辑",
        "expected_effect": "控制输出处理批次", "risk": "低", "priority": 1,
        "bottleneck_triggers": [], "keywords": ["output", "chunk"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "vllm_enable_v1_multiprocessing", "seq": 40,
        "name": "V1 多进程",
        "category": "scheduling", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_ENABLE_V1_MULTIPROCESSING", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置对应环境变量", "tuning_guidance": "框架级功能",
        "expected_effect": "启用多进程", "risk": "低", "priority": 1,
        "bottleneck_triggers": [], "keywords": ["multiprocessing"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "vllm_dp_size", "seq": 41,
        "name": "VLLM_DP_SIZE",
        "category": "parallel", "config_type": "env_var", "action_type": "tune",
        "enabled_check": {"type": "env_var", "var": "VLLM_DP_SIZE", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置 `export VLLM_DP_SIZE=N`", "tuning_guidance": "增大可线性提升吞吐",
        "expected_effect": "数据并行提升吞吐", "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["dp", "data_parallel", "VLLM_DP_SIZE"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "vllm_pp_layer_partition", "seq": 42,
        "name": "PP 层分区策略",
        "category": "parallel", "config_type": "env_var", "action_type": "tune",
        "enabled_check": {"type": "env_var_present", "var": "VLLM_PP_LAYER_PARTITION"},
        "default_enabled": False, "default_value": None,
        "operation": "设置 `export VLLM_PP_LAYER_PARTITION=\"...\"`", "tuning_guidance": "影响 PP 负载均衡",
        "expected_effect": "优化流水线并行负载均衡", "risk": "中", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["pp", "partition", "pipeline"],
        "conflicts_with": [], "requires": [], "applicable_when": {"pp_size_gte": 2},
        "optimization_goal": ["throughput"],
    },
    # ============================================================
    # 三、vLLM-Ascend 特有 — 3.1 环境变量类 (序号 43-55)
    # ============================================================
    {
        "id": "ascend_enable_mlapo", "seq": 43,
        "name": "MLAPO 优化",
        "category": "compute", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_MLAPO", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_MLAPO=1`", "tuning_guidance": "DeepSeek W8A8 场景",
        "expected_effect": "提升性能但消耗更多显存", "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["MLAPO", "DeepSeek"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "ascend_enable_nz", "seq": 44,
        "name": "NZ 格式优化",
        "category": "compute", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_NZ", "value": "2"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_NZ=2`（尽可能启用 NZ 格式）",
        "tuning_guidance": "0=关/1=仅量化/2=尽可能，NZ 格式提升矩阵运算效率",
        "expected_effect": "优化数据布局，提升 Cube 核利用率和计算效率",
        "risk": "低", "priority": 5,
        "bottleneck_triggers": [
            {"dim": "compute_ratio", "op": "gte", "val": 0.4, "weight": 0.5},
        ],
        "keywords": ["cube_utilization", "Cube", "MatMul", "计算效率", "NZ", "FRACTAL_NZ"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "ascend_fusion_transpose_kv", "seq": 45,
        "name": "融合 KV Cache Block 转置",
        "category": "op_fusion", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_FUSION_OP_TRANSPOSE_KV_CACHE_BY_BLOCK", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "默认开启", "tuning_guidance": "减少 KV Cache 操作开销",
        "expected_effect": "减少 KV Cache 操作开销", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["transpose", "kv_cache"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "ascend_enable_fused_mc2", "seq": 46,
        "name": "融合 MC2 算子",
        "category": "communication", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_FUSED_MC2", "value": "1"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_FUSED_MC2=1`",
        "tuning_guidance": "MoE+EP 场景必开",
        "expected_effect": "融合 MC2 算子，减少 MoE 通信开销",
        "risk": "低", "priority": 6,
        "bottleneck_triggers": [
            {"dim": "is_moe", "op": "eq", "val": True, "weight": 0.8},
            {"dim": "comm_ratio", "op": "gte", "val": 0.1, "weight": 0.6},
        ],
        "keywords": ["MC2", "MoE", "fused", "通信", "expert"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "ascend_matmul_allreduce", "seq": 47,
        "name": "MatMul+AllReduce 融合",
        "category": "communication", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_MATMUL_ALLREDUCE", "value": "1"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_MATMUL_ALLREDUCE=1`",
        "tuning_guidance": "TP 场景必开，仅 A2 芯片",
        "expected_effect": "将 AllReduce 通信与 MatMul 计算重叠，减少通信等待时间",
        "risk": "低", "priority": 6,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.1, "weight": 0.8},
            {"dim": "tp_size", "op": "gte", "val": 2, "weight": 0.7},
        ],
        "keywords": ["communication", "通信", "allreduce", "overlap", "掩盖", "mc2", "MatMul"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "ascend_flashcomm1", "seq": 48,
        "name": "FlashComm1 通信优化",
        "category": "communication", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_FLASHCOMM1", "value": "1"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_FLASHCOMM1=1`",
        "tuning_guidance": "高并发 TP 场景",
        "expected_effect": "FlashComm1 通信计算 overlap",
        "risk": "中", "priority": 5,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.15, "weight": 0.7},
        ],
        "keywords": ["flashcomm", "通信", "communication", "overlap"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "ascend_flashcomm2", "seq": 49,
        "name": "FlashComm2 TP group",
        "category": "communication", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var_present", "var": "VLLM_ASCEND_FLASHCOMM2_PARALLEL_SIZE"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_FLASHCOMM2_PARALLEL_SIZE=N`",
        "tuning_guidance": "需配合 layer_sharding",
        "expected_effect": "FlashComm2 通信优化",
        "risk": "高", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.2, "weight": 0.6},
        ],
        "keywords": ["flashcomm2", "通信", "layer_sharding"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "ascend_mlp_gate_up_prefetch", "seq": 50,
        "name": "gate_up 权重预取大小",
        "category": "bandwidth", "config_type": "env_var", "action_type": "tune",
        "enabled_check": {"type": "env_var_present", "var": "VLLM_ASCEND_MLP_GATE_UP_PREFETCH_SIZE"},
        "default_enabled": True, "default_value": "18MB",
        "operation": "设置 `export VLLM_ASCEND_MLP_GATE_UP_PREFETCH_SIZE=<bytes>`",
        "tuning_guidance": "根据模型权重调整", "expected_effect": "优化权重预取",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["prefetch", "gate_up", "MLP", "bandwidth"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "ascend_mlp_down_prefetch", "seq": 51,
        "name": "down_proj 权重预取大小",
        "category": "bandwidth", "config_type": "env_var", "action_type": "tune",
        "enabled_check": {"type": "env_var_present", "var": "VLLM_ASCEND_MLP_DOWN_PREFETCH_SIZE"},
        "default_enabled": True, "default_value": "18MB",
        "operation": "设置 `export VLLM_ASCEND_MLP_DOWN_PREFETCH_SIZE=<bytes>`",
        "tuning_guidance": "根据模型权重调整", "expected_effect": "优化权重预取",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["prefetch", "down_proj", "MLP", "bandwidth"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "ascend_context_parallel", "seq": 52,
        "name": "Context Parallel 长序列并行",
        "category": "parallel", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_CONTEXT_PARALLEL", "value": "1"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_CONTEXT_PARALLEL=1`",
        "tuning_guidance": "长序列场景", "expected_effect": "长序列多卡并行",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [], "keywords": ["context_parallel", "长序列", "long_sequence"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "dynamic_eplb", "seq": 53,
        "name": "动态 EPLB",
        "category": "scheduling", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "DYNAMIC_EPLB", "value": "true"},
        "default_enabled": False, "default_value": "false",
        "operation": "设置 `export DYNAMIC_EPLB=true`",
        "tuning_guidance": "MoE 专家负载均衡", "expected_effect": "运行时动态调整专家分布",
        "risk": "低", "priority": 5,
        "bottleneck_triggers": [
            {"dim": "is_moe", "op": "eq", "val": True, "weight": 0.7},
        ],
        "keywords": ["EPLB", "expert", "MoE", "负载均衡", "load_balance"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "ascend_balance_scheduling", "seq": 54,
        "name": "多卡均衡调度",
        "category": "scheduling", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_BALANCE_SCHEDULING", "value": "1"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_BALANCE_SCHEDULING=1`",
        "tuning_guidance": "多卡场景", "expected_effect": "多卡间均衡调度",
        "risk": "低", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "tp_size", "op": "gte", "val": 2, "weight": 0.5},
        ],
        "keywords": ["balance", "均衡", "调度", "多卡"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "compile_custom_kernels", "seq": 55,
        "name": "编译自定义 NPU 算子",
        "category": "compile", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "COMPILE_CUSTOM_KERNELS", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "设置 `export COMPILE_CUSTOM_KERNELS=1`",
        "tuning_guidance": "确保自定义算子可用", "expected_effect": "启用自定义 NPU 算子",
        "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["custom_kernels", "compile"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    # ============================================================
    # 三、3.2 additional_config 配置类 (序号 56-79)
    # ============================================================
    {
        "id": "pa_shape_list", "seq": 56,
        "name": "指定高效 PA shape",
        "category": "compute", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "pa_shape_list"},
        "default_enabled": False, "default_value": None,
        "operation": "添加 `--additional-config '{\"pa_shape_list\":[...]}'`",
        "tuning_guidance": "选择更快的 attention 算子 shape",
        "expected_effect": "优化 PagedAttention 算子性能",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "compute_ratio", "op": "gte", "val": 0.4, "weight": 0.5},
        ],
        "keywords": ["pa_shape", "attention", "PagedAttention", "FusedInferAttentionScore"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "fuse_qknorm_rope", "seq": 57,
        "name": "融合 QKNorm+RoPE",
        "category": "op_fusion", "config_type": "additional_config", "action_type": "skip",
        "enabled_check": {"type": "additional_config", "key": "ascend_compilation_config.fuse_qknorm_rope", "value": True},
        "default_enabled": True, "default_value": True,
        "operation": "配置 ascend_compilation_config.fuse_qknorm_rope=true",
        "tuning_guidance": "减少中间张量", "expected_effect": "融合 QKNorm 和 RoPE 算子",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["qknorm", "rope", "fusion"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "fuse_allreduce_rms", "seq": 58,
        "name": "融合 AllReduce+AddRMSNorm",
        "category": "communication", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "ascend_compilation_config.fuse_allreduce_rms", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"ascend_compilation_config\":{\"fuse_allreduce_rms\":true}}'`",
        "tuning_guidance": "减少通信同步开销，TP 场景",
        "expected_effect": "融合 AllReduce+Add+RMSNorm，减少通信同步开销",
        "risk": "低", "priority": 6,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.1, "weight": 0.7},
            {"dim": "tp_size", "op": "gte", "val": 2, "weight": 0.6},
        ],
        "keywords": ["allreduce", "rmsnorm", "fusion", "通信", "AddRmsNorm"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "npugraph_ex_enable", "seq": 59,
        "name": "npugraph_ex 后端",
        "category": "compile", "config_type": "additional_config", "action_type": "skip",
        "enabled_check": {"type": "additional_config", "key": "npugraph_ex_config.enable", "value": True},
        "default_enabled": True, "default_value": True,
        "operation": "配置 npugraph_ex_config.enable=true", "tuning_guidance": "Fx 图由 npugraph_ex 编译",
        "expected_effect": "启用 npugraph_ex 编译后端", "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["npugraph", "torchair", "graph"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "npugraph_ex_static_kernel", "seq": 60,
        "name": "静态 kernel 编译",
        "category": "compile", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "npugraph_ex_config.enable_static_kernel", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"npugraph_ex_config\":{\"enable_static_kernel\":true}}'`",
        "tuning_guidance": "固定 shape 场景提升性能",
        "expected_effect": "静态 kernel 编译优化",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.2, "weight": 0.4},
        ],
        "keywords": ["static_kernel", "npugraph", "编译", "compile"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "xlite_graph_enabled", "seq": 61,
        "name": "Xlite 全图编译",
        "category": "compile", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "xlite_graph_config.enabled", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"xlite_graph_config\":{\"enabled\":true}}'`",
        "tuning_guidance": "不兼容投机解码和 PP>1",
        "expected_effect": "Xlite 全图编译优化",
        "risk": "高", "priority": 5,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.3, "weight": 0.6},
        ],
        "keywords": ["xlite", "全图", "graph", "编译", "compile"],
        "conflicts_with": ["speculative_decoding", "pipeline_parallel_size"], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "xlite_graph_full_mode", "seq": 62,
        "name": "Xlite 全图模式",
        "category": "compile", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "xlite_graph_config.full_mode", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"xlite_graph_config\":{\"full_mode\":true}}'`",
        "tuning_guidance": "更激进的图优化",
        "expected_effect": "更激进的全图优化",
        "risk": "高", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.3, "weight": 0.5},
        ],
        "keywords": ["xlite", "full_mode", "全图"],
        "conflicts_with": ["speculative_decoding"], "requires": ["xlite_graph_enabled"],
        "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "weight_prefetch_enabled", "seq": 63,
        "name": "统一权重预取",
        "category": "bandwidth", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "weight_prefetch_config.enabled", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"weight_prefetch_config\":{\"enabled\":true}}'`",
        "tuning_guidance": "attn/mlp/moe 权重预取",
        "expected_effect": "预取权重减少等待时间",
        "risk": "低", "priority": 6,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.2, "weight": 0.6},
            {"dim": "compute_ratio", "op": "lte", "val": 0.6, "weight": 0.4},
        ],
        "keywords": ["prefetch", "权重预取", "weight", "bandwidth", "MLP", "attention"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "weight_prefetch_ratio", "seq": 64,
        "name": "权重预取比例",
        "category": "bandwidth", "config_type": "additional_config", "action_type": "tune",
        "enabled_check": {"type": "additional_config", "key": "weight_prefetch_config.prefetch_ratio"},
        "default_enabled": False, "default_value": None,
        "operation": "配置 weight_prefetch_config.prefetch_ratio",
        "tuning_guidance": "控制预取数据量", "expected_effect": "精细控制预取比例",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["prefetch", "ratio"],
        "conflicts_with": [], "requires": ["weight_prefetch_enabled"], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "recompute_scheduler_enable", "seq": 65,
        "name": "重计算调度器",
        "category": "memory", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "recompute_scheduler_enable", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"recompute_scheduler_enable\":true}'`",
        "tuning_guidance": "重计算释放中间激活值",
        "expected_effect": "减少显存占用，支持更大 batch",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "gpu_mem_util", "op": "gte", "val": 0.95, "weight": 0.6},
        ],
        "keywords": ["recompute", "重计算", "显存", "memory", "activation"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "enable_kv_nz", "seq": 66,
        "name": "KV Cache NZ 格式",
        "category": "memory", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "enable_kv_nz", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"enable_kv_nz\":true}'`",
        "tuning_guidance": "仅 MLA+PD 分离 D 节点",
        "expected_effect": "KV Cache NZ 格式优化",
        "risk": "中", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["kv_nz", "NZ", "KV cache"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "finegrained_tp_oproj", "seq": 67,
        "name": "O-proj 独立 TP",
        "category": "parallel", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "finegrained_tp_config.oproj_tensor_parallel_size"},
        "default_enabled": False, "default_value": "0",
        "operation": "配置 finegrained_tp_config.oproj_tensor_parallel_size",
        "tuning_guidance": "仅图模式+PD 分离 D 节点",
        "expected_effect": "O-proj 层独立 TP 大小",
        "risk": "高", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["finegrained", "oproj", "tp"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "finegrained_tp_lmhead", "seq": 68,
        "name": "LM Head 独立 TP",
        "category": "parallel", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "finegrained_tp_config.lmhead_tensor_parallel_size"},
        "default_enabled": False, "default_value": "0",
        "operation": "配置 finegrained_tp_config.lmhead_tensor_parallel_size",
        "tuning_guidance": "减少 LM Head 通信",
        "expected_effect": "LM Head 层独立 TP",
        "risk": "高", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["finegrained", "lmhead", "tp"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "finegrained_tp_mlp", "seq": 69,
        "name": "MLP 独立 TP",
        "category": "parallel", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "finegrained_tp_config.mlp_tensor_parallel_size"},
        "default_enabled": False, "default_value": "0",
        "operation": "配置 finegrained_tp_config.mlp_tensor_parallel_size",
        "tuning_guidance": "为 MLP 设不同 TP",
        "expected_effect": "MLP 层独立 TP",
        "risk": "高", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["finegrained", "mlp", "tp"],
        "conflicts_with": [], "requires": [], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "enable_shared_expert_dp", "seq": 70,
        "name": "共享专家数据并行",
        "category": "parallel", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "enable_shared_expert_dp", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"enable_shared_expert_dp\":true}'`",
        "tuning_guidance": "需 EP+TP>1",
        "expected_effect": "共享专家数据并行",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [
            {"dim": "is_moe", "op": "eq", "val": True, "weight": 0.6},
        ],
        "keywords": ["shared_expert", "dp", "MoE", "expert"],
        "conflicts_with": [], "requires": ["enable_expert_parallel"], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "eplb_dynamic", "seq": 71,
        "name": "动态专家负载均衡 (additional_config)",
        "category": "scheduling", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "eplb_config.dynamic_eplb", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"eplb_config\":{\"dynamic_eplb\":true}}'`",
        "tuning_guidance": "运行时动态调整专家分布",
        "expected_effect": "MoE 专家动态负载均衡",
        "risk": "低", "priority": 5,
        "bottleneck_triggers": [{"dim": "is_moe", "op": "eq", "val": True, "weight": 0.7}],
        "keywords": ["eplb", "expert", "MoE", "负载均衡", "load_balance"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "eplb_expert_map_path", "seq": 72,
        "name": "专家映射表路径",
        "category": "scheduling", "config_type": "additional_config", "action_type": "tune",
        "enabled_check": {"type": "additional_config", "key": "eplb_config.expert_map_path"},
        "default_enabled": False, "default_value": None,
        "operation": "配置 eplb_config.expert_map_path",
        "tuning_guidance": "预定义专家映射", "expected_effect": "精确控制专家分布",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["expert_map", "eplb"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "eplb_num_redundant_experts", "seq": 73,
        "name": "冗余专家数量",
        "category": "scheduling", "config_type": "additional_config", "action_type": "tune",
        "enabled_check": {"type": "additional_config", "key": "eplb_config.num_redundant_experts"},
        "default_enabled": False, "default_value": "0",
        "operation": "配置 eplb_config.num_redundant_experts",
        "tuning_guidance": "提升负载均衡能力", "expected_effect": "增加冗余专家提升均衡",
        "risk": "中", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["redundant", "expert", "eplb"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "eplb_policy_type", "seq": 74,
        "name": "EPLB 策略类型",
        "category": "scheduling", "config_type": "additional_config", "action_type": "skip",
        "enabled_check": {"type": "additional_config", "key": "eplb_config.eplb_policy_type"},
        "default_enabled": True, "default_value": "1",
        "operation": "配置 eplb_config.eplb_policy_type",
        "tuning_guidance": "0=default/1=flashlb/2=random/3=swift",
        "expected_effect": "选择负载均衡策略", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["eplb", "policy", "flashlb"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "enable_cpu_binding", "seq": 75,
        "name": "CPU 核绑定",
        "category": "scheduling", "config_type": "additional_config", "action_type": "skip",
        "enabled_check": {"type": "additional_config", "key": "enable_cpu_binding", "value": True},
        "default_enabled": True, "default_value": True,
        "operation": "配置 enable_cpu_binding=true",
        "tuning_guidance": "减少调度抖动", "expected_effect": "CPU 核绑定减少抖动",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["cpu_binding", "绑核"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "slo_limits_dynamic_batch", "seq": 76,
        "name": "动态 batch SLO 限制",
        "category": "scheduling", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "SLO_limits_for_dynamic_batch"},
        "default_enabled": False, "default_value": "-1",
        "operation": "添加 `--additional-config '{\"SLO_limits_for_dynamic_batch\":100}'`",
        "tuning_guidance": "动态调整 token budget",
        "expected_effect": "基于 SLO 动态调整 batch 大小",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [], "keywords": ["SLO", "dynamic_batch", "TPOT"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "multistream_overlap_shared_expert", "seq": 77,
        "name": "多流 overlap 共享专家",
        "category": "overlap", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "multistream_overlap_shared_expert", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"multistream_overlap_shared_expert\":true}'`",
        "tuning_guidance": "shared 与 routed expert 并行",
        "expected_effect": "共享专家与路由专家并行执行",
        "risk": "中", "priority": 5,
        "bottleneck_triggers": [{"dim": "is_moe", "op": "eq", "val": True, "weight": 0.7}],
        "keywords": ["multistream", "overlap", "shared_expert", "MoE"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "multistream_overlap_gate", "seq": 78,
        "name": "多流 overlap gate 计算",
        "category": "overlap", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "multistream_overlap_gate", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"multistream_overlap_gate\":true}'`",
        "tuning_guidance": "gate 与其他计算并行",
        "expected_effect": "gate 计算与其他计算并行",
        "risk": "中", "priority": 4,
        "bottleneck_triggers": [{"dim": "is_moe", "op": "eq", "val": True, "weight": 0.6}],
        "keywords": ["multistream", "overlap", "gate", "MoE"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["latency", "throughput"],
    },
    {
        "id": "enable_async_exponential", "seq": 79,
        "name": "异步指数运算",
        "category": "overlap", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "enable_async_exponential", "value": True},
        "default_enabled": False, "default_value": False,
        "operation": "添加 `--additional-config '{\"enable_async_exponential\":true}'`",
        "tuning_guidance": "异步执行指数运算",
        "expected_effect": "异步指数运算减少等待",
        "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["async", "exponential", "异步"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency", "throughput"],
    },
    # ============================================================
    # 三、3.3 自定义 CANN 融合算子 (序号 80-84)
    # ============================================================
    {
        "id": "add_rms_norm_bias", "seq": 80,
        "name": "融合 Add+RMSNorm+Bias",
        "category": "op_fusion", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": None,
        "operation": "自动启用", "tuning_guidance": "减少 kernel launch",
        "expected_effect": "融合 Add+RMSNorm+Bias 算子", "risk": "低", "priority": 3,
        "bottleneck_triggers": [], "keywords": ["add_rms_norm", "AddRmsNormBias", "fusion"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "matmul_allreduce_add_rmsnorm", "seq": 81,
        "name": "融合 MatMul+AllReduce+Add+RMSNorm",
        "category": "op_fusion", "config_type": "additional_config", "action_type": "enable",
        "enabled_check": {"type": "additional_config", "key": "ascend_compilation_config.fuse_allreduce_rms", "value": True},
        "default_enabled": False, "default_value": None,
        "operation": "需开启 fuse_allreduce_rms",
        "tuning_guidance": "TP 场景减少通信同步",
        "expected_effect": "融合 MatMul+AllReduce+Add+RMSNorm",
        "risk": "低", "priority": 6,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.1, "weight": 0.7},
        ],
        "keywords": ["matmul_allreduce", "rmsnorm", "fusion", "通信"],
        "conflicts_with": [], "requires": ["fuse_allreduce_rms"], "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency"],
    },
    {
        "id": "transpose_kv_cache_by_block", "seq": 82,
        "name": "KV Cache Block 转置融合",
        "category": "op_fusion", "config_type": "env_var", "action_type": "skip",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_FUSION_OP_TRANSPOSE_KV_CACHE_BY_BLOCK", "value": "1"},
        "default_enabled": True, "default_value": "1",
        "operation": "默认开启", "tuning_guidance": "减少 KV Cache 操作开销",
        "expected_effect": "KV Cache Block 转置融合", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["transpose", "kv_cache", "block"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "moe_gating_top_k", "seq": 83,
        "name": "MoE 门控 TopK",
        "category": "compute", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": None,
        "operation": "自动启用", "tuning_guidance": "高效专家选择",
        "expected_effect": "MoE 门控 TopK 优化", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["gating", "topk", "MoE"],
        "conflicts_with": [], "requires": [], "applicable_when": {"is_moe": True},
        "optimization_goal": ["latency"],
    },
    {
        "id": "sparse_flash_attention", "seq": 84,
        "name": "稀疏 Flash Attention",
        "category": "compute", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": None,
        "operation": "自动启用", "tuning_guidance": "稀疏注意力减少计算",
        "expected_effect": "稀疏 Flash Attention 优化", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["sparse", "flash_attention"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    # ============================================================
    # 三、3.4 架构级优化特性 (序号 85-87)
    # ============================================================
    {
        "id": "acl_graph_mode", "seq": 85,
        "name": "ACL Graph 模式",
        "category": "compile", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "serve_arg_absent", "arg": "--enforce-eager"},
        "default_enabled": True, "default_value": None,
        "operation": "非 enforce_eager 时自动启用",
        "tuning_guidance": "FULL/PIECEWISE 模式",
        "expected_effect": "NPU 图捕获与回放", "risk": "低", "priority": 5,
        "bottleneck_triggers": [], "keywords": ["ACL", "graph", "图模式"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "camem_allocator", "seq": 86,
        "name": "CaMemAllocator",
        "category": "memory", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": None,
        "operation": "自动启用", "tuning_guidance": "sleep/wake_up 模式",
        "expected_effect": "CANN 可插拔内存分配器", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["CaMemAllocator", "memory", "allocator"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["throughput"],
    },
    {
        "id": "pyhccl_backend", "seq": 87,
        "name": "pyhccl 通信后端",
        "category": "communication", "config_type": "auto", "action_type": "skip",
        "enabled_check": {"type": "always_false"}, "default_enabled": True, "default_value": None,
        "operation": "自动启用", "tuning_guidance": "NPU 专用集合通信",
        "expected_effect": "Python 封装 HCCL 通信", "risk": "低", "priority": 2,
        "bottleneck_triggers": [], "keywords": ["pyhccl", "HCCL", "通信"],
        "conflicts_with": [], "requires": [], "applicable_when": {},
        "optimization_goal": ["latency", "throughput"],
    },
    # ============================================================
    # 额外：原有 skill 中的关键项（确保不遗漏）
    # ============================================================
    {
        "id": "task_queue_enable_2", "seq": 100,
        "name": "二级流水 (TASK_QUEUE_ENABLE=2)",
        "category": "dispatch", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "TASK_QUEUE_ENABLE", "value": "2"},
        "default_enabled": False, "default_value": None,
        "operation": "设置 `export TASK_QUEUE_ENABLE=2`，启用 Level 2 算子下发流水线优化",
        "tuning_guidance": "减少算子下发间隔，不能与图模式同时开启",
        "expected_effect": "减少算子下发间隔，降低 host scheduling overhead，提升 NPU 利用率",
        "risk": "低", "priority": 8,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.3, "weight": 0.9},
        ],
        "keywords": ["free", "空闲", "idle", "host scheduling", "算子下发", "dispatch", "TASK_QUEUE_ENABLE"],
        "conflicts_with": ["graph_mode"], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "prefetch_mlp", "seq": 101,
        "name": "MLP Prefetch",
        "category": "compute", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "VLLM_ASCEND_ENABLE_PREFETCH_MLP", "value": "1"},
        "default_enabled": False, "default_value": "0",
        "operation": "设置 `export VLLM_ASCEND_ENABLE_PREFETCH_MLP=1`，启用 MLP 权重预取",
        "tuning_guidance": "将 MLP weight loading 与 attention 计算重叠",
        "expected_effect": "将 MLP weight loading 与 attention 计算重叠，减少每个 decode step 延迟",
        "risk": "低", "priority": 7,
        "bottleneck_triggers": [
            {"dim": "free_ratio", "op": "gte", "val": 0.2, "weight": 0.6},
            {"dim": "compute_ratio", "op": "lte", "val": 0.6, "weight": 0.4},
        ],
        "keywords": ["MLP", "prefetch", "预取", "weight loading", "attention", "decode", "TPOT"],
        "conflicts_with": [], "requires": [],
        "applicable_when": {},
        "optimization_goal": ["latency"],
    },
    {
        "id": "hccl_aiv_mode", "seq": 102,
        "name": "AIV 通信模式",
        "category": "communication", "config_type": "env_var", "action_type": "enable",
        "enabled_check": {"type": "env_var", "var": "HCCL_OP_EXPANSION_MODE", "value": "AIV"},
        "default_enabled": False, "default_value": None,
        "operation": "设置 `export HCCL_OP_EXPANSION_MODE=\"AIV\"`，启用 AIV 通信模式",
        "tuning_guidance": "使用 AIV 核执行通信操作，释放 AIC 核用于计算",
        "expected_effect": "使用 AIV 核执行通信操作，释放 AIC 核用于计算，提升通算并行度",
        "risk": "低", "priority": 6,
        "bottleneck_triggers": [
            {"dim": "comm_ratio", "op": "gte", "val": 0.1, "weight": 0.7},
            {"dim": "tp_size", "op": "gte", "val": 2, "weight": 0.5},
        ],
        "keywords": ["communication", "通信", "allreduce", "allgather", "HCCL", "AIV", "tp"],
        "conflicts_with": [], "requires": [],
        "applicable_when": {"tp_size_gte": 2},
        "optimization_goal": ["latency", "throughput"],
    },
]
